# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "UON CS4S Introduction Workshop"
email: "daniel.hickmott@uon.edu.au"
contact: "Daniel Hickmott"
baseurl: "/intro-2019"
drive_url: "https://drive.google.com/uc?export=view&id="

# Content Pages Paths
glossary_path: "/glossary"
resources_path: "/resources"

# Day 1 Paths
day1_path: "/day1/"
introduction_path: "/day1/introduction/"
unplugged_path: "/day1/unplugged/"
blocks_path: "/day1/blocks/"
creative_computing_path: "/day1/creative_computing/"
introduction_path: "/day1/introduction/"

# Day 2 Paths
day2_path: "/day2/"
blocks_to_text_path: "/day2/blocks_to_text/"
physical_computing_path: "/day2/physical_computing/"
lesson_planning_path: "/day2/lesson_planning/"
sharing_path: "/day2/sharing/"

# Build settings
markdown: kramdown
